import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import ThemeProvider  from "./components/ThemeProvider";
import AnimatedTransition from "./components/AnimatedTransition";
import { Toaster } from "sonner";
import { ClerkProvider } from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IntelliCheck - AI-Powered Quiz Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
                <NavBar />
                <Toaster position="top-center" />
              <AnimatedTransition>
                {children}
              </AnimatedTransition>

              <footer className="text-center py-6 text-gray-600 dark:text-gray-400 border-t border-gray-200 dark:border-gray-700 mt-10">
                © {new Date().getFullYear()} <span className="font-semibold text-blue-600">QuizGenie</span> - <span className="font-semibold">Ba Hoa NGUYEN</span>
              </footer>
            
            </ThemeProvider>
          </body>
        </html>
    </ClerkProvider>
  );
}
