import { z } from "zod";

export const saveQuizRequestSchema = z.object({
    title: z.string().trim().min(1, "Title too short").max(100, "Title too long"),
    subject: z.string().trim().min(1, "Subject too short").max(100, "Subject too long"),
    description: z.string().trim().min(1, "Description too short").max(1000, "Description too long"),
    questions: z.array(
        z.object({
            question: z.string().min(1),
            correctAnswer: z
                .string()
                .length(1)
                .transform((val) => val.toUpperCase())
                .refine((val) => ["A", "B", "C", "D"].includes(val), {
                    error: "Must be A, B, C, or D"
                }),
            optionA: z.string().min(1),
            optionB: z.string().min(1),
            optionC: z.string().min(1),
            optionD: z.string().min(1),
        })
    )
        .min(1)
})


// Validate the saveQuizResponse generated by the backend
export const saveQuizResponseSchema = z.object({
    success: z.boolean(),
    quiz: z.object({
        id: z.string().min(1),
        title: z.string().min(1),
        subject: z.string(),
        questionCount: z.number().int().nonnegative(),
        createdAt: z.string()
    })
})